name: Bot bourse

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # toutes les 30 min (plus stable que 5 min)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python main.py
